### ISSUE TITLE
Absolute paths 

### ISSUE THREAD

**Issue by sw005320** [mmaciej2/speech-separation#1]
@mmaciej2, the sources seem to have several absolute paths, and people outside CLSP could not make it run.

E.g.,
1. https://github.com/mmaciej2/speech-separation/search?q=%2Fexport&unscoped_q=%2Fexport
2. https://github.com/mmaciej2/speech-separation/blob/8a0fb1246cc6d3629827c99bff19659b489a8af1/tools/eval_to_wav.py#L5
3. all filel lists

Could you fix them?

**Comment by mmaciej2** [comment]
@sw005320,
I am aware of all of that. Part of the problem is that the code I use for generating spectrograms and reconstructing is Greg's audio tool stuff. I shouldn't be putting his personal code on my github, and even beyond that, there's compatibility issues with it. I think the only acceptable solution would be for me to implement my own spectrogram/feature extraction code and use that instead. I think that is something that is definitely worth doing, but I have not done it because I imagine the time investment will not be negligible.

**Comment by sw005320** [comment]
You can use [librosa](https://librosa.github.io/librosa/) instead of implementing it by yourself, which saves your time. Now you have a solid baseline, easy to compare it. It's better to have the reproducibility.

**Comment by mmaciej2** [comment]
Ok. I can start working on including the feature generation in my code so the repo can run end-to-end.
